spring:
    application:
        name: shopping-cart
    datasource:
      url: jdbc:postgresql://localhost:5432/shopping-cart-db
      username: postgres
      password: 267115
    jpa:
        hibernate:
#            ddl-auto: update
            ddl-auto: create
        show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
    servlet:
      multipart:
        enabled: true
        max-file-size: 10MB
        max-request-size: 10MB

auth:
  token:
    expirationInMils: 3600000
    jwtSecret: 36763979244226452948404D635166546A576D5A7134743777217A25432A462D

api-prefix: api/v1
